Areas/ControlPanel/Controllers/UlogeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TCorp.Components;
using TCorp.Controllers;
using TCorp.EntityFramework;

namespace TCorp.Areas.ControlPanel.Controllers {
    public class UlogeController : SuperAdminController {

        private RoleComponent rc = new RoleComponent();

        public ActionResult Index() {
            using (TCorpDbEntities ctx = new TCorpDbEntities()) {
                var roles = ctx.Roles.AsNoTracking().ToList();
                return View(roles);
            }
        }

        public ActionResult Details(int id = 0) {
            using (TCorpDbEntities ctx = new TCorpDbEntities()) {
                Role role = ctx.Roles.AsNoTracking().SingleOrDefault(r => r.Id == id);
                if (role == null) {
                    return HttpNotFound();
                }
                int roleId = authComponent.GetCurrentUser().Role.Id;
                ViewBag.CategoriesTable = rc.CreateHtmlTable(roleId, true);
                return View(role);
            }
        }

        public ActionResult Create() {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Role role) {
            using (TCorpDbEntities ctx = new TCorpDbEntities()) {
                //validacija
                ctx.Roles.Add(role);
                ctx.SaveChanges();
                return RedirectToAction("Index");

            }
        }

        public ActionResult Edit(int Id = 0) {
            using (TCorpDbEntities ctx = new TCorpDbEntities()) {
                Role role = ctx.Roles.AsNoTracking().SingleOrDefault(r => r.Id == Id);
                if (role == null) {
                    return HttpNotFound();
                }
                ViewBag.CategoriesTable = rc.CreateHtmlTable(role.Id);
                return View(role);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int Id, string Name, bool ManagerPrivilages, List<int> Visible) {
            using (TCorpDbEntities ctx = new TCorpDbEntities()) {
                //validacija
                Role role = ctx.Roles.SingleOrDefault(r => r.Id == Id);
                if (role == null) {
                    return HttpNotFound("Invalid id");
                }
                //role.Update(Name, MaxDiscount);
                role.Name = Name;
                role.ManagerPrivilages = ManagerPrivilages;
                ctx.Database.ExecuteSqlCommand("DELETE FROM Category_Role WHERE role_id = '" + role.Id + "'");
                foreach (var categoryId in Visible) {
                    Category c = ctx.Categories.Single(ca => ca.Id == categoryId);
                    role.Category.Add(c);
                }
                ctx.Database.ExecuteSqlCommand("DELETE FROM Category_Role_MaxDiscount WHERE role_id = '" + role.Id + "'");
                string[] discountIndex = Request.Form.GetValues("Discount.Index");
                foreach (var categoryId in discountIndex) {
                    Category_Role_MaxDiscount maxDisount = new Category_Role_MaxDiscount();
                    maxDisount.category_id = int.Parse(categoryId);
                    maxDisount.role_id = role.Id;
                    maxDisount.MaxDiscount = double.Parse(Request.Form[String.Format("Discount[{0}].Value", categoryId)]) / 100;
                    role.Category_Role_MaxDiscount.Add(maxDisount);
                }
                ctx.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        public ActionResult Delete(int id = 0) {
            using (TCorpDbEntities ctx = new TCorpDbEntities()) {
                Role role = ctx.Roles.Find(id);
                if (role == null) {
                    return HttpNotFound();
                }
                ctx.Roles.Remove(role);
                ctx.SaveChanges();
                return RedirectToAction("Index");
            }
        }
    }
}

Areas/ControlPanel/Views/Uloge/Create.cshtml
@model TCorp.EntityFramework.Role

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Role</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <p>
            <input type="submit" value="Create" class="btn btn-t"/>
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new{@class = "btn"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Areas/ControlPanel/Views/Uloge/Delete.cshtml
@model TCorp.EntityFramework.Role

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Role</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" class="btn btn-t"/> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Areas/ControlPanel/Views/Uloge/Details.cshtml
@model TCorp.EntityFramework.Role

@{
    ViewBag.Title = "Detalji";
}

<h2>Profil: @Model.Name</h2>

<fieldset>
    <legend>Kategorije</legend>

</fieldset>

@Html.Raw(ViewBag.CategoriesTable)
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }, new{@class = "btn btn-t"})
	<br>
	<br>
    @Html.ActionLink("Back to List", "Index", null, new{@class = "btn"})
</p>
<script>
$(document).ready(function () {
    $('a.link-toggler').click(function (e) {
        if (e.target != this) return;
	    $(this).parent().children('ul.tree').toggle(300);
    });
	$('a.link-toggler').each(function (index) {
	    $(this).click();
	});
	$('label.nav-header').click(function (e) {
	    if (e.target != this) return;
	    $(this).parent().parent().children('ul.tree').toggle(300);
	});
});
</script>

Areas/ControlPanel/Views/Uloge/Edit.cshtml
@model TCorp.EntityFramework.Role

@{
    ViewBag.Title = "Uredi";
}

<h2>Uredi profil: @Model.Name</h2>

@using (Html.BeginForm("Edit", "Uloge", FormMethod.Post)) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Uloge</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
			Naziv Uloge:
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            Mogućnost ručne korekcije cijene mobilnih uređaja:
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ManagerPrivilages)
            @Html.ValidationMessageFor(model => model.ManagerPrivilages)
        </div>
    </fieldset>
    @Html.Raw(ViewBag.CategoriesTable)

    <p>
        <input type="submit" value="Spremi" class="btn btn-t" />
    </p>
    
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new{@class = "btn"})
</div>
<script>
    $(document).ready(function () {
        $('a.link-toggler').click(function (e) {
            if (e.target != this) return;
            $(this).parent().children('ul.tree').toggle(300);
        });
        $('a.link-toggler').each(function (index) {
            $(this).click();
        });
        $('label.nav-header').click(function (e) {
            if (e.target != this) return;
            $(this).parent().parent().children('ul.tree').toggle(300);
        });
        $('.visibilityCheckbox').click(function (e) {
            var isChecked = $(this).prop('checked');
            if (isChecked) {
                var categoryId = $(this).prop('value');
                $("li").has(".visibilityCheckbox[value='" + categoryId + "']").children(".link-toggler").children(".visibilityCheckbox").prop("checked", true)
            }
            $(this).parent().parent().find('.visibilityCheckbox').each(function () {
                if (e.target != this) $(this).prop('checked', isChecked);
            });
        });
        $('.discountText').change(function (e) {
            var value = $(this).val();
            $(this).parent().parent().find('.discountText').each(function () {
                if (e.target != this) $(this).val(value);
            });
        });
    });
</script>

Areas/ControlPanel/Views/Uloge/Index.cshtml
@model IEnumerable<TCorp.EntityFramework.Role>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, null,  new{@class = "btn"})
</p>
<table class="table table-hover filterable">
    <thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Name)
			</th>
			<th width="144px"></th>
			
		</tr>
	</thead>
	<tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new{@class = "btn btn-mini btn-t"}) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }, new{@class = "btn btn-mini btn-t"}) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { onclick = "return confirm('Are you sure?');", @class = "btn btn-mini btn-t" })
            </td>
        </tr>
    }
	</tbody>
</table>
<script src="@Url.Content("~/Scripts/jquery.table-filter.js")"></script>


<script type="text/javascript">
    $(document).ready(function () {
        $('table.filterable').addTableFilter({
            labelText: "Filtriraj tablicu",
            size: 48
        });
    });
</script>